

"""
Identify_coordingates.py

This script takes a TSV file generated by Biomart. The script assumes feature start and
stop locations are the second and thrid columns in the file. Using the start and stop 
feature locations, the script finds the boundries of the gene model and can calculate
coordinate locations upstrem and downstream of the gene model for the placement of SNPs
the are too far away for Gviz to plot nicely.

Usage:
To change the upstream and downstream locations calculated, the variables UPMOD and 
DOWNMOD need to adjusted in the script. These variables represent how far away, 
upstream and downstream, SNP features are located as a percentage of the gene models
entire length in base pairs. 

run the script on the command line:

	python identify_coordinates.py gene_biomart.tsv

output is printed directly to the screen (stdout)
"""


import sys

UPMOD = .35
DOWNMOD = .25

with open(sys.argv[1]) as inf:

	header = inf.readline()

	coordinates = []

	for line in inf.readlines():

		coords = line.split('\t')[1:3]
		coordinates.append(int(coords[0]))
		coordinates.append(int(coords[1]))

	coordmin = min(coordinates)
	coordmax = max(coordinates)
	coordrange = coordmax - coordmin
	upstream = coordmin - int(UPMOD*coordrange)
	downstream = coordmax + int(DOWNMOD*coordrange)

	print "Gene start: {}, Gene end: {}, Upstream SNP: {}, Downstream SNP: {}".format(
		coordmin, coordmax, upstream, downstream)